### ISSUE TITLE
TimeSynchronizer while some of the topics not working

### ISSUE THREAD

**Issue by qingchunlizhi** [ros2/message_filters#63]
Hi, I use the python version of the message filters now. However, when I subscribe to multiple topics, if one or more of them don't work, the other normal topics can't be synchronized. Therefore, how to ensure the synchronization of the normal topics and give up these wrong topics ? 
        Thanks!

**Comment by clalancette** [comment]
These kinds of questions are best asked at https://answers.ros.org, which is our central questions-and-answers site.  There may be answers there that address your question already, and if not you should get a better response there.

Since this isn't a bug in this package, I'm going to close this out.
